apiVersion: v1
kind: Service
metadata:
  name: {{ include "vaadin-chart.fullname" . }}
  labels:
    app: vaadin
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: vaadin
