apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaadin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaadin
  template:
    metadata:
      labels:
        app: vaadin
    spec:
      containers:
      - name: vaadin
        image: samarth1311/vaadin:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
---


apiVersion: v1
kind: Service
metadata:
  name: vaadin-service
  labels:
    app: vaadin
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 31123
  selector:
    app: vaadin

